#### flipkart_data_scrap:-

In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [92]:
import warnings
warnings.filterwarnings("ignore")

In [93]:
from bs4 import BeautifulSoup
from urllib.request import urlopen,Request
import requests

In [95]:
url="https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.brand%255B%255D%3DApple&sort=price_asc"

In [96]:
r=requests.get(url)
print(r)

<Response [200]>

In [97]:
soup=BeautifulSoup(r.text,"lxml")
# print(soup)

### scrap product name:=

In [99]:
all_info =soup.find_all("div",class_="yKfJKb row")
link=all_info.find("a",class_="_9QVEpD").get("href")
print(link)
# print(all_info)
# print(len(all_info))
required_cols=["product_name","actual_price","sale_price","review & ratings","offer","camera","processor","memory","battery","display"]

AttributeError: ResultSet object has no attribute 'find'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [15]:
product_name=all_info[0].find_all("div",class_="KzDlHZ")[0].text

In [16]:
rating_number=all_info[0].find_all("div",class_="XQDdHH")[0].text
# print(rating_number)

In [17]:
review_and_rating=all_info[0].find_all("span",class_="Wphh3N")[0].text
# print(review_and_rating)

In [18]:
specification=all_info[0].find_all("div",class_="_6NESgJ")[0]
print(specification)
# specify_all=specification.find_all("li")
 # print(specify_all)
# memory_info=specification.find_all("li")[0].text
# print(memory_info)

<div class="_6NESgJ"><ul class="G4BRas"><li class="J+igdf">64 GB ROM</li><li class="J+igdf">11.94 cm (4.7 inch) Retina HD Display</li><li class="J+igdf">12MP Rear Camera | 7MP Front Camera</li><li class="J+igdf">A13 Bionic Chip with 3rd Gen Neural Engine Processor</li><li class="J+igdf">Water and Dust Resistant (1 meter for Upto 30 minutes, IP67)</li><li class="J+igdf">Fast Charge Capable</li><li class="J+igdf">Wireless charging (Works with Qi Chargers | Qi Chargers are Sold Separately</li><li class="J+igdf">1 year warranty for phone and 1 year warranty for in Box Accessories.</li></ul></div>

In [39]:
memory_info=specification.find_all("li")[0].text
print(memory_info)

64 GB ROM

In [40]:
display=specification.find_all("li")[1].text

'11.94 cm (4.7 inch) Retina HD Display'

In [41]:
camera=specification.find_all("li")[2].text

'12MP Rear Camera | 7MP Front Camera'

In [42]:
processor=specification.find_all("li")[3].text

'A13 Bionic Chip with 3rd Gen Neural Engine Processor'

In [43]:
water_resistance=specification.find_all("li")[4].text

'Water and Dust Resistant (1 meter for Upto 30 minutes, IP67)'

In [44]:
charging=specification.find_all("li")[5].text

'Fast Charge Capable'

In [45]:
wireless_charging=specification.find_all("li")[6].text

'Wireless charging (Works with Qi Chargers | Qi Chargers are Sold Separately'

In [46]:
warranty=specification.find_all("li")[7].text

'1 year warranty for phone and 1 year warranty for in Box Accessories.'

In [47]:
price=all_info[0].find_all("div",class_="Nx9bqj _4b5DiR")[0].text
print(price)

₹39,900

In [50]:
# actual_price=all_info[0].find_all("div",class_="yRaY8j ZYYwLA").text

In [48]:
data_cols=["Product Name","Actual Price","Sale Price","Review & Ratings","Offer","Camera","Processor","Memory","battery","Display","Rating Number",]

In [50]:
rating_number=all_info[0].find_all("div",class_="XQDdHH")[0].text

In [57]:
pd.DataFrame(data)

,Product Name,Actual Price,Sale Price,Review & Ratings,Offer,Camera,Processor,Memory,battery,Display,Rating Number
0,"Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)","Apple iPhone SE (Red, 64 GB)"
1,"1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews","1,54,623 Ratings & 11,955 Reviews"
2,"[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]","[[4.5, []]]"
3,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM,64 GB ROM
4,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display,11.94 cm (4.7 inch) Retina HD Display
...,...,...,...,...,...,...,...,...,...,...,...
475,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera,12MP + 12MP | 12MP Front Camera
476,"A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor","A15 Bionic Chip, 6 Core Processor Processor"
477,None,None,None,None,None,None,None,None,None,None,None
478,"₹64,900","₹64,900","₹64,900","₹64,900","₹64,900","₹64,900","₹64,900","₹64,900","₹64,900","₹64,900","₹64,900"
479,no offer,no offer,no offer,no offer,no offer,no offer,no offer,no offer,no offer,no offer,no offer

# overall apple analysis

In [84]:
data = {
    "Product Name": [],
    "Review & Ratings": [],
    "Rating Number": [],
    "Memory": [],
    "Display": [],
    "Camera": [],
    "Processor": [],
    "Water Resistance": [],
    "Fast Charging": [],
    "Wireless Charging": [],
    "Warranty": [],
    "Actual Price": [],
    "Sale Price": [],
    "Offer": [],
}

In [85]:
for i in range(2,27):
    url = "https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&p%5B%5D=facets.brand%255B%255D%3DApple&sort=price_asc&page=" + str(i)
    r = requests.get(url)
    soup = BeautifulSoup(r.text, "lxml")

    # list of product cards on THIS page
    all_info = soup.find_all("div", class_="tUxRFH")  # adjust if needed
    
    for card in all_info:          # I call it 'card' instead of 'contain'
    
        # -------- Product name --------
        name_tag = card.find("div", class_="KzDlHZ")
        product_name = name_tag.get_text(strip=True) if name_tag else None
        data["Product Name"].append(product_name)
    
        # -------- Rating & reviews --------
        # rr is a single tag, not a list → use find(), not find_all()
        rr = card.find("span", class_="Wphh3N")   # e.g. "4.5★ 1,54,623 Ratings & 11,955 Reviews"
        if rr is None:
            review_and_rating = None
            rating_number = None
        else:
            review_and_rating = rr.get_text(strip=True)
    
            # number of ratings only (if available)
            rating_num_tag = card.find("div", class_="XQDdHH")
            rating_number = rating_num_tag.get_text(strip=True) if rating_num_tag else None
    
        data["Review & Ratings"].append(review_and_rating)
        data["Rating Number"].append(rating_number)
    
        # -------- Specifications (bullets) --------
        spec_block = card.find("div", class_="_6NESgJ")
    
        # default: everything None
        memory = display = camera = processor = None
        water_res = fast_chg = wireless_chg = warranty = None
    
        if spec_block:
            li_texts = [li.get_text(strip=True) for li in spec_block.find_all("li")]
    
            # classify each bullet into the right column
            for text in li_texts:
                t = text.lower()
    
                if "rom" in t:
                    memory = text
                elif "display" in t:
                    display = text
                elif "camera" in t:
                    camera = text
                elif "bionic" in t or "chip" in t or "processor" in t:
                    processor = text
                elif "water" in t or "ip67" in t or "ip68" in t:
                    water_res = text
                elif "fast charge" in t or "fast charging" in t:
                    fast_chg = text
                elif "wireless charging" in t:
                    wireless_chg = text
                elif "warranty" in t:
                    warranty = text
    
        # add specs to data
        data["Memory"].append(memory)
        data["Display"].append(display)
        data["Camera"].append(camera)
        data["Processor"].append(processor)
        data["Water Resistance"].append(water_res)
        data["Fast Charging"].append(fast_chg)
        data["Wireless Charging"].append(wireless_chg)
        data["Warranty"].append(warranty)
    
        # -------- Actual price --------
        actual_price_tag = card.find("div", class_="yRaY8j ZYYwLA")
        my_price = actual_price_tag.get_text(strip=True) if actual_price_tag else None
        data["Actual Price"].append(my_price)
    
        # -------- Sale price --------
        sale_tag = card.find("div", class_="Nx9bqj _4b5DiR")
        sale_price = sale_tag.get_text(strip=True) if sale_tag else None
        data["Sale Price"].append(sale_price)
    
        # -------- Offer text --------
        offer_tag = card.find("div", class_="UkUFwK")
        if offer_tag:
            data["Offer"].append(offer_tag.get_text(strip=True))
        else:
            data["Offer"].append("no offer")

In [86]:
import numpy as np

In [87]:
df=pd.DataFrame(data)
print(df)

                                         Product Name  \
0                  Apple iPhone 14 (Midnight, 256 GB)
1                      Apple iPhone 16 (Teal, 128 GB)
2                      Apple iPhone 16 (Pink, 128 GB)
3                     Apple iPhone 16 (White, 128 GB)
4                     Apple iPhone 16 (Black, 128 GB)
..                                                ...
569     Apple iPhone 17 Pro Max (Cosmic Orange, 1 TB)
570     Apple iPhone 15 Pro Max (Blue Titanium, 1 TB)
571  Apple iPhone 15 Pro Max (Natural Titanium, 1 TB)
572    Apple iPhone 15 Pro Max (Black Titanium, 1 TB)
573    Apple iPhone 15 Pro Max (White Titanium, 1 TB)

                    Review & Ratings Rating Number      Memory  \
0    3,20,202 Ratings&11,894 Reviews           4.6  256 GB ROM
1     1,82,314 Ratings&5,755 Reviews           4.6  128 GB ROM
2     1,82,314 Ratings&5,755 Reviews           4.6  128 GB ROM
3     1,82,314 Ratings&5,755 Reviews           4.6  128 GB ROM
4     1,82,314 Ratings&5,755 Reviews           4.6  128 GB ROM
..                               ...           ...         ...
569           295 Ratings&29 Reviews           4.8    1 TB ROM
570        2,817 Ratings&196 Reviews           4.6    1 TB ROM
571        2,817 Ratings&196 Reviews           4.6    1 TB ROM
572        2,817 Ratings&196 Reviews           4.6    1 TB ROM
573        2,817 Ratings&196 Reviews           4.6    1 TB ROM

                                          Display  \
0    15.49 cm (6.1 inch) Super Retina XDR Display
1    15.49 cm (6.1 inch) Super Retina XDR Display
2    15.49 cm (6.1 inch) Super Retina XDR Display
3    15.49 cm (6.1 inch) Super Retina XDR Display
4    15.49 cm (6.1 inch) Super Retina XDR Display
..                                            ...
569  17.53 cm (6.9 inch) Super Retina XDR Display
570  17.02 cm (6.7 inch) Super Retina XDR Display
571  17.02 cm (6.7 inch) Super Retina XDR Display
572  17.02 cm (6.7 inch) Super Retina XDR Display
573  17.02 cm (6.7 inch) Super Retina XDR Display

                                     Camera  \
0           12MP + 12MP | 12MP Front Camera
1           48MP + 12MP | 12MP Front Camera
2           48MP + 12MP | 12MP Front Camera
3           48MP + 12MP | 12MP Front Camera
4           48MP + 12MP | 12MP Front Camera
..                                      ...
569  48MP + 48MP + 48MP | 18MP Front Camera
570  48MP + 12MP + 12MP | 12MP Front Camera
571  48MP + 12MP + 12MP | 12MP Front Camera
572  48MP + 12MP + 12MP | 12MP Front Camera
573  48MP + 12MP + 12MP | 12MP Front Camera

                                       Processor Water Resistance  \
0    A15 Bionic Chip, 6 Core Processor Processor             None
1           A18 Chip, 6 Core Processor Processor             None
2           A18 Chip, 6 Core Processor Processor             None
3           A18 Chip, 6 Core Processor Processor             None
4           A18 Chip, 6 Core Processor Processor             None
..                                           ...              ...
569         A19 Chip, 6 Core Processor Processor             None
570     A17 Pro Chip, 6 Core Processor Processor             None
571     A17 Pro Chip, 6 Core Processor Processor             None
572     A17 Pro Chip, 6 Core Processor Processor             None
573     A17 Pro Chip, 6 Core Processor Processor             None

    Fast Charging Wireless Charging  \
0            None              None
1            None              None
2            None              None
3            None              None
4            None              None
..            ...               ...
569          None              None
570          None              None
571          None              None
572          None              None
573          None              None

                                              Warranty Actual Price  \
0    1 year warranty for phone and 1 year warranty ...         None
1    1 year warranty for phone and 1 year warranty ...         None
2    1 year warranty for phone and 1 year warranty ...         None
3    1 year warranty for phone and 1 year warranty ...         None
4    1 year warranty for phone and 1 year warranty ...         None
..                                                 ...          ...
569                Apple One (1) Year Limited Warranty         None
570  1 year warranty for phone and 1 year warranty ...         None
571  1 year warranty for phone and 1 year warranty ...         None
572  1 year warranty for phone and 1 year warranty ...         None
573  1 year warranty for phone and 1 year warranty ...         None

    Sale Price     Offer
0      ₹64,900  no offer
1      ₹69,900  no offer
2      ₹69,900  no offer
3      ₹69,900  no offer
4      ₹69,900  no offer
..         ...       ...
569  ₹1,89,900  no offer
570  ₹1,99,900  no offer
571  ₹1,99,900  no offer
572  ₹1,99,900  no offer
573  ₹1,99,900  no offer

[574 rows x 14 columns]

In [88]:
df[1:10]

,Product Name,Review & Ratings,Rating Number,Memory,Display,Camera,Processor,Water Resistance,Fast Charging,Wireless Charging,Warranty,Actual Price,Sale Price,Offer
1,"Apple iPhone 16 (Teal, 128 GB)","1,82,314 Ratings&5,755 Reviews",4.6,128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,None,"₹69,900",no offer
2,"Apple iPhone 16 (Pink, 128 GB)","1,82,314 Ratings&5,755 Reviews",4.6,128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,None,"₹69,900",no offer
3,"Apple iPhone 16 (White, 128 GB)","1,82,314 Ratings&5,755 Reviews",4.6,128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,None,"₹69,900",no offer
4,"Apple iPhone 16 (Black, 128 GB)","1,82,314 Ratings&5,755 Reviews",4.6,128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,None,"₹69,900",no offer
5,"Apple iPhone 16 (Ultramarine, 128 GB)","1,82,314 Ratings&5,755 Reviews",4.6,128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,None,"₹69,900",no offer
6,"Apple iPhone 14 Plus (Starlight, 128 GB)","86,718 Ratings&4,758 Reviews",4.6,128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,None,"₹69,900",no offer
7,"Apple iPhone 16 Plus (Black, 128 GB)","3,957 Ratings&211 Reviews",4.6,128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,"₹79,900","₹71,999",9% off
8,"Apple iPhone 16 Plus (White, 128 GB)","3,957 Ratings&211 Reviews",4.6,128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,"₹79,900","₹71,999",9% off
9,"Apple iPhone 16 Plus (Pink, 128 GB)","3,957 Ratings&211 Reviews",4.6,128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",None,None,None,1 year warranty for phone and 1 year warranty ...,"₹79,900","₹71,999",9% off

In [89]:
df.to_csv("D:/web scraping/scraped excel sheet/filtered_apple_25_page_data.csv",index=False)

# motorala data scrap

In [165]:
data_moto = {
    "Product Name": [],
    "Review & Ratings": [],
    "Rating Number": [],
    "Memory": [],
    "Display": [],
    "Camera": [],
    "Processor": [],
    "Water Resistance": [],
    "Fast Charging": [],
    "Wireless Charging": [],
    "Warranty": [],
    "Actual Price": [],
    "Sale Price": [],
    "Offer": [],
    "Battery":[]
    
}

In [167]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
url_moto="https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3DMotoROLA"
r_moto=requests.get(url_moto)
soup_moto=BeautifulSoup(r_moto.text,"lxml")
link_moto=soup_moto.find("a",class_="_9QVEpD").get("href")
actual_link_moto="https://www.flipkart.com/"+link_moto
print(actual_link_moto)

https://www.flipkart.com//search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3DMotoROLA&page=2

In [168]:
for i in range(2,17):
    my_url_moto = "https://www.flipkart.com//search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3DMotoROLA&page=" + str(i)
    my_r_moto = requests.get(my_url_moto)
    my_soup_moto = BeautifulSoup(my_r_moto.text, "lxml")

    # list of product cards on THIS page
    all_info_moto = my_soup_moto.find_all("div", class_="yKfJKb row")  # adjust if needed
    
    for card_moto in all_info_moto:          # I call it 'card' instead of 'contain'
    
        # -------- Product name --------
        name_tag_moto = card_moto.find("div", class_="KzDlHZ")
        product_name_moto = name_tag_moto.get_text(strip=True) if name_tag_moto else None
        data_moto["Product Name"].append(product_name_moto)

    
        # -------- Rating & reviews --------
        # rr is a single tag, not a list → use find(), not find_all()
        rr_moto = card_moto.find("span", class_="Wphh3N")   # e.g. "4.5★ 1,54,623 Ratings & 11,955 Reviews"
        if rr_moto is None:
            review_and_rating_moto = None
            rating_number_moto= None
        else:
            review_and_rating_moto = rr_moto.get_text(strip=True)
    
            # number of ratings only (if available)
            rating_num_tag_moto = card_moto.find("div", class_="XQDdHH")
            rating_number_moto = rating_num_tag_moto.get_text(strip=True) if rating_num_tag_moto else None
    
        data_moto["Review & Ratings"].append(review_and_rating_moto)
        data_moto["Rating Number"].append(rating_number_moto)
    
        # -------- Specifications (bullets) --------
        spec_block_moto = card_moto.find("div", class_="_6NESgJ")
    
        # default: everything None
        memory_moto = display_moto = camera_moto = processor_moto = None
        water_res_moto = fast_chg_moto = wireless_chg_moto = warranty_moto = battery_moto =None
    
        if spec_block_moto:
            li_texts_moto = [li.get_text(strip=True) for li in spec_block_moto.find_all("li")]
    
            # classify each bullet into the right column
            for text in li_texts_moto:
                t_moto = text.lower()
    
                if "rom" in t_moto or "ram" in t_moto:
                    memory_moto = text
                elif "display" in t_moto:
                    display_moto = text
                elif "camera" in t_moto:
                    camera_moto = text
                elif "bionic" in t_moto or "chip" in t_moto or "processor" in t_moto:
                    processor_moto = text
                elif "water" in t_moto or "ip67" in t_moto or "ip68" in t_moto:
                    water_res_moto = text
                elif "fast charge" in t_moto or "fast charging" in t_moto:
                    fast_chg_moto = text
                elif "wireless charging" in t_moto:
                    wireless_chg_moto = text
                elif "warranty" in t_moto or "year" in t_moto or "months" in t_moto:
                    warranty_moto = text
                elif "battery" in t_moto or "mah" in t_moto:
                    battery_moto = text
        data_moto["Memory"].append(memory_moto)
        data_moto["Display"].append(display_moto)
        data_moto["Camera"].append(camera_moto)
        data_moto["Processor"].append(processor_moto)
        data_moto["Water Resistance"].append(water_res_moto)
        data_moto["Fast Charging"].append(fast_chg_moto)
        data_moto["Wireless Charging"].append(wireless_chg_moto)
        data_moto["Warranty"].append(warranty_moto)
        data_moto["Battery"].append(battery_moto)
           
        
        
    
        # -------- Actual price --------
        actual_price_tag_moto = card_moto.find("div", class_="yRaY8j ZYYwLA")
        my_price_moto = actual_price_tag_moto.get_text(strip=True) if actual_price_tag_moto else None
        data_moto["Actual Price"].append(my_price_moto)
    
        # -------- Sale price --------
        sale_tag_moto = card_moto.find("div", class_="Nx9bqj _4b5DiR")
        sale_price_moto = sale_tag_moto.get_text(strip=True) if sale_tag_moto else None
        data_moto["Sale Price"].append(sale_price_moto)
    
        # -------- Offer text --------
        offer_tag_moto = card_moto.find("div", class_="UkUFwK")
        offer_moto = offer_tag_moto.get_text(strip=True) if offer_tag_moto else "no offer"
        data_moto["Offer"].append(offer_moto)

In [169]:
import numpy as np
import pandas as pd
# df_moto=pd.DataFrame(data_moto)
# print(df_moto)
for k, v in data_moto.items():
    print(k, len(v))

Product Name 318
Review & Ratings 318
Rating Number 318
Memory 318
Display 318
Camera 318
Processor 318
Water Resistance 318
Fast Charging 318
Wireless Charging 318
Warranty 318
Actual Price 318
Sale Price 318
Offer 318
Battery 318

In [170]:
df_moto=pd.DataFrame(data_moto)
print(df_moto)

                                          Product Name  \
0                 MOTOROLA g35 5G (Leaf Green, 128 GB)
1             MOTOROLA g35 5G (Midnight Black, 128 GB)
2                  MOTOROLA g35 5G (Guava Red, 128 GB)
3             Motorola g45 5G (Brilliant Blue, 128 GB)
4            Motorola g45 5G (Brilliant Green, 128 GB)
..                                                 ...
313        MOTOROLA Razar 50 Flip (Beach Sand, 256 GB)
314     MOTOROLA Razar 50 Flip (Spritz Orange, 256 GB)
315             MOTOROLA Razar 40 (Sage Green, 256 GB)
316  MOTOROLA Razr 60 Ultra (Pantone Mountain Trail...
317   MOTOROLA Razr 60 Ultra (Pantone Rio Red, 512 GB)

                   Review & Ratings Rating Number  \
0    1,06,580 Ratings&6,800 Reviews           4.2
1    1,06,580 Ratings&6,800 Reviews           4.2
2    1,06,580 Ratings&6,800 Reviews           4.2
3      52,332 Ratings&3,060 Reviews           4.3
4      52,332 Ratings&3,060 Reviews           4.3
..                              ...           ...
313             3 Ratings&0 Reviews             4
314             3 Ratings&0 Reviews             4
315            16 Ratings&0 Reviews           4.2
316             6 Ratings&1 Reviews             5
317             6 Ratings&1 Reviews             5

                                           Memory  \
0    4 GB RAM | 128 GB ROM | Expandable Upto 1 TB
1    4 GB RAM | 128 GB ROM | Expandable Upto 1 TB
2    4 GB RAM | 128 GB ROM | Expandable Upto 1 TB
3    4 GB RAM | 128 GB ROM | Expandable Upto 1 TB
4    4 GB RAM | 128 GB ROM | Expandable Upto 1 TB
..                                            ...
313                         8 GB RAM | 256 GB ROM
314                         8 GB RAM | 256 GB ROM
315                         8 GB RAM | 256 GB ROM
316                        16 GB RAM | 512 GB ROM
317                        16 GB RAM | 512 GB ROM

                                   Display                          Camera  \
0    17.07 cm (6.72 inch) Full HD+ Display  50MP + 8MP | 16MP Front Camera
1    17.07 cm (6.72 inch) Full HD+ Display  50MP + 8MP | 16MP Front Camera
2    17.07 cm (6.72 inch) Full HD+ Display  50MP + 8MP | 16MP Front Camera
3          16.51 cm (6.5 inch) HD+ Display  50MP + 2MP | 16MP Front Camera
4          16.51 cm (6.5 inch) HD+ Display  50MP + 2MP | 16MP Front Camera
..                                     ...                             ...
313            17.53 cm (6.9 inch) Display                50MP Rear Camera
314            17.53 cm (6.9 inch) Display                50MP Rear Camera
315            17.53 cm (6.9 inch) Display                64MP Rear Camera
316           17.68 cm (6.96 inch) Display                50MP Rear Camera
317           17.68 cm (6.96 inch) Display                50MP Rear Camera

                         Processor Water Resistance Fast Charging  \
0                   T760 Processor             None          None
1                   T760 Processor             None          None
2                   T760 Processor             None          None
3    Snapdragon 6s Gen 3 Processor             None          None
4    Snapdragon 6s Gen 3 Processor             None          None
..                             ...              ...           ...
313                           None             None          None
314                           None             None          None
315                           None             None          None
316                           None             None          None
317                           None             None          None

    Wireless Charging                                           Warranty  \
0                None      1 Year on Handset and 6 Months on Accessories
1                None      1 Year on Handset and 6 Months on Accessories
2                None      1 Year on Handset and 6 Months on Accessories
3                None  1 Year Warranty on Handset and 6 Months Warran...
4                None  1 Year Warranty on Handset and 6 Months Warran...
..                ...                                                ...
313              None                                             1 Year
314              None                                             1 Year
315              None                      1 Year Manufacturing Warranty
316              None                              1 Year Brand Warranty
317              None                              1 Year Brand Warranty

    Actual Price Sale Price    Offer           Battery
0        ₹12,499     ₹9,999  20% off  5000 mAh Battery
1        ₹12,499     ₹9,999  20% off  5000 mAh Battery
2        ₹12,499     ₹9,999  20% off  5000 mAh Battery
3        ₹12,999     ₹9,999  23% off  5000 mAh Battery
4        ₹12,999     ₹9,999  23% off  5000 mAh Battery
..           ...        ...      ...               ...
313      ₹74,999    ₹59,999  20% off  4200 mAh Battery
314      ₹79,999    ₹72,999   8% off  4200 mAh Battery
315      ₹99,999    ₹88,888  11% off  4200 mAh Battery
316    ₹1,09,000    ₹89,899  17% off  4700 mAh Battery
317    ₹1,09,000    ₹89,900  17% off  4700 mAh Battery

[318 rows x 15 columns]

In [171]:
df_moto[5:15]

,Product Name,Review & Ratings,Rating Number,Memory,Display,Camera,Processor,Water Resistance,Fast Charging,Wireless Charging,Warranty,Actual Price,Sale Price,Offer,Battery
5,"Motorola g45 5G (Viva Magenta, 128 GB)","52,332 Ratings&3,060 Reviews",4.3,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) HD+ Display,50MP + 2MP | 16MP Front Camera,Snapdragon 6s Gen 3 Processor,None,None,None,1 Year Warranty on Handset and 6 Months Warran...,"₹12,999","₹9,999",23% off,5000 mAh Battery
6,"Motorola G40 Fusion (Frosted Champagne, 64 GB)","33,697 Ratings&3,715 Reviews",4.2,4 GB RAM | 64 GB ROM,17.22 cm (6.78 inch) Full HD+ Display,64MP + 8MP + 2MP | 16MP Front Camera,Qualcomm Snapdragon 732G Processor,None,None,None,1 Year on Handset and 6 Months on Accessories,"₹16,999","₹10,999",35% off,6000 mAh Battery
7,"Motorola G32 (Satin Silver, 64 GB)","47,044 Ratings&3,964 Reviews",4.2,4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) Full HD+ Display,50MP + 8MP + 2MP | 16MP Front Camera,Qualcomm Snapdragon 680 Processor,None,None,None,1 Year on Handset and 6 Months on Accessories,"₹16,999","₹10,999",35% off,5000 mAh Lithium Polymer Battery
8,"Motorola g22 (Cosmic Black, 64 GB)","36,399 Ratings&3,835 Reviews",3.8,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) HD+ Display,50MP + 8MP + 2MP + 2MP | 16MP Front Camera,Mediatek Helio G37 Processor,None,None,None,1 Year on Handset and 6 Months on Accessories,"₹13,999","₹10,999",21% off,5000 mAh Lithium Ion Battery
9,"Motorola G32 (Mineral Gray, 64 GB)","47,044 Ratings&3,964 Reviews",4.2,4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) Full HD+ Display,50MP + 8MP + 2MP | 16MP Front Camera,Qualcomm Snapdragon 680 Processor,None,None,None,1 Year on Handset and 6 Months on Accessories,"₹16,999","₹10,999",35% off,5000 mAh Lithium Polymer Battery
10,"MOTOROLA g35 5G (Midnight Black, 128 GB)","2,352 Ratings&107 Reviews",4.2,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.07 cm (6.72 inch) Full HD+ Display,50MP + 8MP | 16MP Front Camera,T760 Processor,None,None,None,1 Year on Handset and 6 Months on Accessories,"₹15,499","₹11,999",22% off,5000 mAh Battery
11,"Motorola g45 5G (Brilliant Blue, 128 GB)","2,44,409 Ratings&12,158 Reviews",4.3,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) HD+ Display,50MP + 2MP | 16MP Front Camera,Snapdragon 6s Gen 3 Processor,None,None,None,1 Year Warranty on Handset and 6 Months Warran...,"₹14,999","₹11,999",20% off,5000 mAh Battery
12,"MOTOROLA g35 5G (Leaf Green, 128 GB)","2,352 Ratings&107 Reviews",4.2,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.07 cm (6.72 inch) Full HD+ Display,50MP + 8MP | 16MP Front Camera,T760 Processor,None,None,None,1 Year on Handset and 6 Months on Accessories,"₹15,499","₹11,999",22% off,5000 mAh Battery
13,"Motorola g45 5G (Brilliant Green, 128 GB)","2,44,409 Ratings&12,158 Reviews",4.3,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) HD+ Display,50MP + 2MP | 16MP Front Camera,Snapdragon 6s Gen 3 Processor,None,None,None,1 Year Warranty on Handset and 6 Months Warran...,"₹14,999","₹11,999",20% off,5000 mAh Battery
14,"MOTOROLA g35 5G (Guava Red, 128 GB)","2,352 Ratings&107 Reviews",4.2,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.07 cm (6.72 inch) Full HD+ Display,50MP + 8MP | 16MP Front Camera,T760 Processor,None,None,None,1 Year on Handset and 6 Months on Accessories,"₹15,499","₹11,999",22% off,5000 mAh Battery

In [146]:
df_moto.to_csv("D:/web scraping/scraped excel sheet/filtered_moto_page_data.csv",index=False)

# realme scrap

In [172]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
url_realme="https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3Drealme"
r_realme=requests.get(url_realme)
soup_realme=BeautifulSoup(r_realme.text,"lxml")
link_realme=soup_realme.find("a",class_="_9QVEpD").get("href")
actual_link_realme="https://www.flipkart.com/"+link_realme
print(actual_link_realme)

https://www.flipkart.com//search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3Drealme&page=2

In [173]:
data_realme = {
    "Product Name": [],
    "Review & Ratings": [],
    "Rating Number": [],
    "Memory": [],
    "Display": [],
    "Camera": [],
    "Processor": [],
    "Water Resistance": [],
    "Fast Charging": [],
    "Wireless Charging": [],
    "Warranty": [],
    "Actual Price": [],
    "Sale Price": [],
    "Offer": [],
    "Battery":[]
    
}

In [174]:
for i in range(2,39):
    my_url_realme = "https://www.flipkart.com//search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3Drealme&page=" + str(i)
    my_r_realme = requests.get(my_url_realme)
    my_soup_realme = BeautifulSoup(my_r_realme.text, "lxml")

    # list of product cards on THIS page
    all_info_realme = my_soup_realme.find_all("div", class_="yKfJKb row")  # adjust if needed
    
    for card_realme in all_info_realme:          # I call it 'card' instead of 'contain'
    
        # -------- Product name --------
        name_tag_realme = card_realme.find("div", class_="KzDlHZ")
        product_name_realme = name_tag_realme.get_text(strip=True) if name_tag_realme else None
        data_realme["Product Name"].append(product_name_realme)

    
        # -------- Rating & reviews --------
        # rr is a single tag, not a list → use find(), not find_all()
        rr_realme = card_realme.find("span", class_="Wphh3N")   # e.g. "4.5★ 1,54,623 Ratings & 11,955 Reviews"
        if rr_realme is None:
            review_and_rating_realme = None
            rating_number_realme= None
        else:
            review_and_rating_realme = rr_realme.get_text(strip=True)
    
            # number of ratings only (if available)
            rating_num_tag_realme = card_realme.find("div", class_="XQDdHH")
            rating_number_realme = rating_num_tag_realme.get_text(strip=True) if rating_num_tag_realme else None
    
        data_realme["Review & Ratings"].append(review_and_rating_realme)
        data_realme["Rating Number"].append(rating_number_realme)
    
        # -------- Specifications (bullets) --------
        spec_block_realme = card_realme.find("div", class_="_6NESgJ")
    
        # default: everything None
        memory_realme = display_realme = camera_realme = processor_realme = None
        water_res_realme = fast_chg_realme = wireless_chg_realme = warranty_realme = battery_realme =None
    
        if spec_block_realme:
            li_texts_realme = [li.get_text(strip=True) for li in spec_block_realme.find_all("li")]
    
            # classify each bullet into the right column
            for text in li_texts_realme:
                t_realme = text.lower()
    
                if "rom" in t_realme or "ram" in t_realme:
                    memory_realme = text
                elif "display" in t_realme:
                    display_realme = text
                elif "camera" in t_realme:
                    camera_realme = text
                elif "bionic" in t_realme or "chip" in t_realme or "processor" in t_realme:
                    processor_realme = text
                elif "water" in t_realme or "ip67" in t_realme or "ip68" in t_realme:
                    water_res_realme = text
                elif "fast charge" in t_realme or "fast charging" in t_realme:
                    fast_chg_realme = text
                elif "wireless charging" in t_realme:
                    wireless_chg_realme = text
                elif "warranty" in t_realme or "year" in t_realme or "months" in t_realme:
                    warranty_realme = text
                elif "battery" in t_realme or "mah" in t_realme:
                    battery_realme = text
        data_realme["Memory"].append(memory_realme)
        data_realme["Display"].append(display_realme)
        data_realme["Camera"].append(camera_realme)
        data_realme["Processor"].append(processor_realme)
        data_realme["Water Resistance"].append(water_res_realme)
        data_realme["Fast Charging"].append(fast_chg_realme)
        data_realme["Wireless Charging"].append(wireless_chg_realme)
        data_realme["Warranty"].append(warranty_realme)
        data_realme["Battery"].append(battery_realme)
           
        
        
    
        # -------- Actual price --------
        actual_price_tag_realme = card_realme.find("div", class_="yRaY8j ZYYwLA")
        my_price_realme = actual_price_tag_realme.get_text(strip=True) if actual_price_tag_realme else None
        data_realme["Actual Price"].append(my_price_realme)
    
        # -------- Sale price --------
        sale_tag_realme = card_realme.find("div", class_="Nx9bqj _4b5DiR")
        sale_price_realme = sale_tag_realme.get_text(strip=True) if sale_tag_realme else None
        data_realme["Sale Price"].append(sale_price_realme)
    
        # -------- Offer text --------
        offer_tag_realme = card_realme.find("div", class_="UkUFwK")
        offer_realme = offer_tag_realme.get_text(strip=True) if offer_tag_realme else "no offer"
        data_realme["Offer"].append(offer_realme)

In [175]:
for k, v in data_realme.items():
    print(k, len(v))

Product Name 823
Review & Ratings 823
Rating Number 823
Memory 823
Display 823
Camera 823
Processor 823
Water Resistance 823
Fast Charging 823
Wireless Charging 823
Warranty 823
Actual Price 823
Sale Price 823
Offer 823
Battery 823

In [176]:
df_realme=pd.DataFrame(data_realme)
print(df_realme)

                                          Product Name  \
0               realme 12x 5G (Woodland Green, 128 GB)
1            realme Narzo 80x 5G (Sunlit Gold, 128 GB)
2              realme Narzo N65 5G (Ambr Gold, 128 GB)
3                 realme P3x 5G (Lunar Silver, 128 GB)
4                realme P3x 5G (Midnight Blue, 128 GB)
..                                                 ...
818                  realme X50 Pro (Rust Red, 128 GB)
819               realme GT 5G (Racing Yellow, 256 GB)
820  realme 15 Pro 5G Game of Thrones L.E (Dragonfi...
821  realme GT7 Dream Edition 5G (Aston Martin Gree...
822               realme X50 Pro 5G (Rust Red, 256 GB)

                   Review & Ratings Rating Number  \
0    1,09,821 Ratings&4,971 Reviews           4.4
1          1,481 Ratings&55 Reviews           4.2
2         6,692 Ratings&279 Reviews           4.3
3        20,745 Ratings&849 Reviews           4.4
4        20,745 Ratings&849 Reviews           4.4
..                              ...           ...
818     8,691 Ratings&1,221 Reviews           4.4
819         614 Ratings&103 Reviews           4.4
820            33 Ratings&6 Reviews           4.7
821                            None          None
822         793 Ratings&121 Reviews           4.4

                                           Memory  \
0    6 GB RAM | 128 GB ROM | Expandable Upto 2 TB
1                           6 GB RAM | 128 GB ROM
2                           6 GB RAM | 128 GB ROM
3                           8 GB RAM | 128 GB ROM
4                           8 GB RAM | 128 GB ROM
..                                            ...
818                         8 GB RAM | 128 GB ROM
819                        12 GB RAM | 256 GB ROM
820                        12 GB RAM | 512 GB ROM
821                        16 GB RAM | 512 GB ROM
822                        12 GB RAM | 256 GB ROM

                                   Display  \
0    17.07 cm (6.72 inch) Full HD+ Display
1             17.07 cm (6.72 inch) Display
2             16.94 cm (6.67 inch) Display
3     17.07 cm (6.72 inch) Full HD Display
4     17.07 cm (6.72 inch) Full HD Display
..                                     ...
818  16.36 cm (6.44 inch) Full HD+ Display
819  16.33 cm (6.43 inch) Full HD+ Display
820            17.27 cm (6.8 inch) Display
821           17.22 cm (6.78 inch) Display
822  16.36 cm (6.44 inch) Full HD+ Display

                                                Camera  \
0                        50MP + 2MP | 8MP Front Camera
1                                     50MP Rear Camera
2                                     50MP Rear Camera
3                  50MP Rear Camera | 8MP Front Camera
4                  50MP Rear Camera | 8MP Front Camera
..                                                 ...
818  64MP + 12MP + 8MP + 2MP | 32MP + 8MP Dual Fron...
819               64MP + 8MP + 2MP | 16MP Front Camera
820                    50MP + 50MP | 50MP Front Camera
821                                   50MP Rear Camera
822  64MP + 12MP + 8MP + 2MP | 32MP + 8MP Dual Fron...

                             Processor Water Resistance Fast Charging  \
0            Dimensity 6100+ Processor             None          None
1                                 None             None          None
2                                 None             None          None
3             Dimensity 6400 Processor             None          None
4             Dimensity 6400 Processor             None          None
..                                 ...              ...           ...
818  Qualcomm Snapdragon 865 Processor             None          None
819  Qualcomm Snapdragon 888 Processor             None          None
820                  7 Gen 4 Processor             None          None
821                               None             None          None
822  Qualcomm Snapdragon 865 Processor             None          None

    Wireless Charging                                           Warranty  \
0                None  1 Year Manufacturer Warranty for Device and 6 ...
1                None  1 Year Manufacturer Warranty for Phone and 6 M...
2                None                                             1 Year
3                None  1 Year Manufacturer Warranty for Device and 6 ...
4                None  1 Year Manufacturer Warranty for Device and 6 ...
..                ...                                                ...
818              None  Brand Warranty of 1 Year Available for Mobile ...
819              None  1 Year Warranty for Mobile and 6 Months for Ac...
820              None  1 Year Manufacturer Warranty for Device and 6 ...
821              None                                    1 Year Warranty
822              None  Brand Warranty of 1 Year Available for Mobile ...

    Actual Price Sale Price     Offer           Battery
0        ₹17,999    ₹12,499   30% off  5000 mAh Battery
1        ₹15,999    ₹12,539   21% off  6000 mAh Battery
2        ₹14,999    ₹12,790   14% off  5000 mAh Battery
3        ₹17,999    ₹12,999   27% off  6000 mAh Battery
4        ₹17,999    ₹12,999   27% off  6000 mAh Battery
..           ...        ...       ...               ...
818         None    ₹41,999  no offer  4200 mAh Battery
819         None    ₹43,999  no offer  4500 mAh Battery
820      ₹49,999    ₹44,999   10% off  7000 mAh Battery
821      ₹59,999    ₹47,999   20% off  7000 mAh Battery
822         None    ₹47,999  no offer  4200 mAh Battery

[823 rows x 15 columns]

In [177]:
df_realme[10:20]

,Product Name,Review & Ratings,Rating Number,Memory,Display,Camera,Processor,Water Resistance,Fast Charging,Wireless Charging,Warranty,Actual Price,Sale Price,Offer,Battery
10,"realme 14X 5G (JWEL RED, 128 GB)","13,411 Ratings&662 Reviews",4.3,6 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP Rear Camera,None,None,None,None,1 YEAR HANDSET 6 MONTHS IN BOX ACCESSORIES,"₹16,999","₹13,999",17% off,6000 mAh Battery
11,"realme 70 TURBO 5G (Turbo Green, 128 GB)","6,262 Ratings&469 Reviews",4.3,6 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Full HD+ Display,50MP Rear Camera,Segment's Fastest Dimensity 7300 Energy 5G Chi...,None,None,None,12 Months Brand warranty,"₹19,999","₹14,396",28% off,5000 mAh Battery
12,"realme 70 TURBO 5G (Turbo Purple, 128 GB)","6,262 Ratings&469 Reviews",4.3,6 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Full HD+ Display,50MP Rear Camera,Segment's Fastest Dimensity 7300 Energy 5G Chi...,None,None,None,12 Months Brand warranty,"₹19,999","₹14,709",26% off,5000 mAh Battery
13,"realme 14x 5G (Jewel Red, 128 GB)","7,993 Ratings&405 Reviews",4.4,8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,999","₹14,957",16% off,6000 mAh Battery
14,"realme Narzo 80x 5G (Sunlit Gold, 128 GB)","1,982 Ratings&77 Reviews",4.3,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹16,999","₹14,999",11% off,6000 mAh Battery
15,"realme P3 5G (Space Silver, 128 GB)","30,948 Ratings&1,977 Reviews",4.4,6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) Full HD+ Display,50MP + 2MP | 16MP Front Camera,6 Gen 4 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹19,999","₹15,999",20% off,6000 mAh Battery
16,"realme P3 5G (Nebula Pink, 128 GB)","30,948 Ratings&1,977 Reviews",4.4,6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) Full HD+ Display,50MP + 2MP | 16MP Front Camera,6 Gen 4 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹19,999","₹15,999",20% off,6000 mAh Battery
17,"realme P3 5G (Comet Grey, 128 GB)","30,948 Ratings&1,977 Reviews",4.4,6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) Full HD+ Display,50MP + 2MP | 16MP Front Camera,6 Gen 4 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹19,999","₹15,999",20% off,6000 mAh Battery
18,"realme P4 5G (Engine Blue, 128 GB)","15,323 Ratings&981 Reviews",4.4,6 GB RAM | 128 GB ROM,17.2 cm (6.77 inch) Display,50MP + 8MP | 16MP Front Camera,Mediatek Dimensity 7400 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹20,999","₹16,999",19% off,7000 mAh Battery
19,"realme P4 5G (Forge Red, 128 GB)","15,323 Ratings&981 Reviews",4.4,6 GB RAM | 128 GB ROM,17.2 cm (6.77 inch) Display,50MP + 8MP | 16MP Front Camera,Mediatek Dimensity 7400 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹20,999","₹16,999",19% off,7000 mAh Battery

In [159]:
df_realme.to_csv("D:/web scraping/scraped excel sheet/filtered_realme_page_data.csv",index=False)

# samsung scrap

In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
url_samsung="https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3DSamsung"
r_samsung=requests.get(url_samsung)
soup_samsung=BeautifulSoup(r_samsung.text,"lxml")
link_samsung=soup_samsung.find("a",class_="_9QVEpD").get("href")
actual_link_samsung="https://www.flipkart.com/"+link_samsung
print(actual_link_samsung)

https://www.flipkart.com//search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3DSamsung&page=2

In [161]:
pip install jupyterlab

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: jupyterlab in c:\programdata\anaconda3\lib\site-packages (4.3.4)
Requirement already satisfied: async-lru>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: ipykernel>=6.5.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (6.25.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (3.1.2)
Requirement already satisfied: jupyter-core in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (5.3.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (2.5.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (0.2.2)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (23.1)
Requirement already satisfied: setuptools>=40.8.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (68.0.0)
Requirement already satisfied: tornado>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (6.3.2)
Requirement already satisfied: traitlets in c:\programdata\anaconda3\lib\site-packages (from jupyterlab) (5.7.1)
Requirement already satisfied: anyio in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab) (3.5.0)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab) (3.4)
Requirement already satisfied: h11>=0.16 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: comm>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (0.1.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (8.15.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (1.5.6)
Requirement already satisfied: psutil in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (5.9.0)
Requirement already satisfied: pyzmq>=20 in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyterlab) (2.1.1)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core->jupyterlab) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core->jupyterlab) (305.1)
Requirement already satisfied: argon2-cffi in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (21.3.0)
Requirement already satisfied: jupyter-events>=0.4.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.6.3)
Requirement already satisfied: jupyter-server-terminals in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (6.5.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.9.2)
Requirement already satisfied: prometheus-client in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.14.1)
Requirement already satisfied: pywinpty in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (2.0.10)
Requirement already satisfied: send2trash in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.17.1)
Requirement already satisfied: websocket-client in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.58.0)
Requirement already satisfied: babel>=2.10 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (2.11.0)
Requirement already satisfied: json5>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (0.9.6)
Requirement already satisfied: jsonschema>=4.18.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (4.25.0)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (2.32.5)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab) (1.2.0)
Requirement already satisfied: pytz>=2015.7 in c:\programdata\anaconda3\lib\site-packages (from babel>=2.10->jupyterlab-server<3,>=2.27.1->jupyterlab) (2023.3.post1)
Requirement already satisfied: backcall in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.0)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.18.1)
Requirement already satisfied: pickleshare in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (2.15.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.4.6)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.28.0)
Requirement already satisfied: entrypoints in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=6.5.0->jupyterlab) (0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=6.5.0->jupyterlab) (2.8.2)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.4.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.4.0->jupyter-server<3,>=2.4.0->jupyterlab) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.4.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.4.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.9.3)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.12.2)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.1.0)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.8.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.5.13)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.5.0)
Requirement already satisfied: tinycss2 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.2.1)
Requirement already satisfied: fastjsonschema in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.16.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.26.16)
Requirement already satisfied: argon2-cffi-bindings in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab) (21.2.0)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from websocket-client->jupyter-server<3,>=2.4.0->jupyterlab) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.8.3)
Collecting fqdn (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab)
  Obtaining dependency information for fqdn from https://files.pythonhosted.org/packages/cf/58/8acf1b3e91c58313ce5cb67df61001fc9dcd21be4fadb76c1a2d540e09ed/fqdn-1.5.1-py3-none-any.whl.metadata
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab)
  Obtaining dependency information for isoduration from https://files.pythonhosted.org/packages/7b/55/e5326141505c5d5e34c5e0935d2908a74e4561eca44108fbfb9c13d2911a/isoduration-20.11.0-py3-none-any.whl.metadata
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonpointer>1.13 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2.1)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab)
  Obtaining dependency information for rfc3987-syntax>=1.1.0 from https://files.pythonhosted.org/packages/7e/71/44ce230e1b7fadd372515a97e32a83011f906ddded8d03e3c6aafbdedbb7/rfc3987_syntax-1.1.0-py3-none-any.whl.metadata
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab)
  Obtaining dependency information for uri-template from https://files.pythonhosted.org/packages/e7/00/3fca040d7cf8a32776d3d81a00c8ee7457e00f80c649f1e4a863c8321ae9/uri_template-1.3.0-py3-none-any.whl.metadata
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab)
  Obtaining dependency information for webcolors>=24.6.0 from https://files.pythonhosted.org/packages/e2/cc/e097523dd85c9cf5d354f78310927f1656c422bd7b2613b2db3e3f9a0f2c/webcolors-25.10.0-py3-none-any.whl.metadata
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.5)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\shubh\appdata\roaming\python\python311\site-packages (from referencing>=0.28.4->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (4.15.0)
Requirement already satisfied: cffi>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (2.4)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.5.1)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (2.0.5)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.5.0->jupyterlab) (0.2.2)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab) (2.21)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab)
  Obtaining dependency information for lark>=1.2.2 from https://files.pythonhosted.org/packages/82/3d/14ce75ef66813643812f3093ab17e46d3a206942ce7376d31ec2d36229e7/lark-1.3.1-py3-none-any.whl.metadata
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: arrow>=0.15.0 in c:\programdata\anaconda3\lib\site-packages (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.2.3)
Downloading rfc3987_syntax-1.1.0-py3-none-any.whl (8.0 kB)
Downloading webcolors-25.10.0-py3-none-any.whl (14 kB)
Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)
Downloading uri_template-1.3.0-py3-none-any.whl (11 kB)
Downloading lark-1.3.1-py3-none-any.whl (113 kB)
   ---------------------------------------- 0.0/113.2 kB ? eta -:--:--
   ---------------------------- ----------- 81.9/113.2 kB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 113.2/113.2 kB 1.6 MB/s eta 0:00:00
Installing collected packages: webcolors, uri-template, lark, fqdn, rfc3987-syntax, isoduration
Successfully installed fqdn-1.5.1 isoduration-20.11.0 lark-1.3.1 rfc3987-syntax-1.1.0 uri-template-1.3.0 webcolors-25.10.0

In [186]:
data_samsung = {
    "Product Name": [],
    "Review & Ratings": [],
    "Rating Number": [],
    "Memory": [],
    "Display": [],
    "Camera": [],
    "Processor": [],
    "Water Resistance": [],
    "Fast Charging": [],
    "Wireless Charging": [],
    "Warranty": [],
    "Actual Price": [],
    "Sale Price": [],
    "Offer": [],
    "Battery":[]
    
}

In [187]:
for i in range(1,44):
    my_url_samsung = "https://www.flipkart.com//search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=price_asc&p%5B%5D=facets.brand%255B%255D%3DSamsung&page=" + str(i)
    my_r_samsung = requests.get(my_url_samsung)
    my_soup_samsung = BeautifulSoup(my_r_samsung.text, "lxml")

    # list of product cards on THIS page
    all_info_samsung = my_soup_samsung.find_all("div", class_="yKfJKb row")  # adjust if needed
    
    for card_samsung in all_info_samsung:          # I call it 'card' instead of 'contain'
    
        # -------- Product name --------
        name_tag_samsung = card_samsung.find("div", class_="KzDlHZ")
        product_name_samsung = name_tag_samsung.get_text(strip=True) if name_tag_samsung else None
        data_samsung["Product Name"].append(product_name_samsung)

    
        # -------- Rating & reviews --------
        # rr is a single tag, not a list → use find(), not find_all()
        rr_samsung = card_samsung.find("span", class_="Wphh3N")   # e.g. "4.5★ 1,54,623 Ratings & 11,955 Reviews"
        if rr_samsung is None:
            review_and_rating_samsung = None
            rating_number_samsung= None
        else:
            review_and_rating_samsung = rr_samsung.get_text(strip=True)
    
            # number of ratings only (if available)
            rating_num_tag_samsung = card_samsung.find("div", class_="XQDdHH")
            rating_number_samsung = rating_num_tag_samsung.get_text(strip=True) if rating_num_tag_samsung else None
    
        data_samsung["Review & Ratings"].append(review_and_rating_samsung)
        data_samsung["Rating Number"].append(rating_number_samsung)
    
        # -------- Specifications (bullets) --------
        spec_block_samsung = card_samsung.find("div", class_="_6NESgJ")
    
        # default: everything None
        memory_samsung = display_samsung = camera_samsung = processor_samsung = None
        water_res_samsung = fast_chg_samsung = wireless_chg_samsung = warranty_samsung = battery_samsung =None
    
        if spec_block_samsung:
            li_texts_samsung = [li.get_text(strip=True) for li in spec_block_samsung.find_all("li")]
    
            # classify each bullet into the right column
            for text in li_texts_samsung:
                t_samsung = text.lower()
    
                if "rom" in t_samsung or "ram" in t_samsung:
                    memory_samsung = text
                elif "display" in t_samsung:
                    display_samsung = text
                elif "camera" in t_samsung:
                    camera_samsung = text
                elif "bionic" in t_samsung or "chip" in t_samsung or "processor" in t_samsung:
                    processor_samsung = text
                elif "water" in t_samsung or "ip67" in t_samsung or "ip68" in t_samsung:
                    water_res_samsung = text
                elif "fast charge" in t_samsung or "fast charging" in t_samsung:
                    fast_chg_samsung = text
                elif "wireless charging" in t_samsung:
                    wireless_chg_samsung = text
                elif "warranty" in t_samsung or "year" in t_samsung or "months" in t_samsung:
                    warranty_samsung = text
                elif "battery" in t_samsung or "mah" in t_samsung:
                    battery_samsung = text
        data_samsung["Memory"].append(memory_samsung)
        data_samsung["Display"].append(display_samsung)
        data_samsung["Camera"].append(camera_samsung)
        data_samsung["Processor"].append(processor_samsung)
        data_samsung["Water Resistance"].append(water_res_samsung)
        data_samsung["Fast Charging"].append(fast_chg_samsung)
        data_samsung["Wireless Charging"].append(wireless_chg_samsung)
        data_samsung["Warranty"].append(warranty_samsung)
        data_samsung["Battery"].append(battery_samsung)
           
        
        
    
        # -------- Actual price --------
        actual_price_tag_samsung = card_samsung.find("div", class_="yRaY8j ZYYwLA")
        my_price_samsung = actual_price_tag_samsung.get_text(strip=True) if actual_price_tag_samsung else None
        data_samsung["Actual Price"].append(my_price_samsung)
    
        # -------- Sale price --------
        sale_tag_samsung = card_samsung.find("div", class_="Nx9bqj _4b5DiR")
        sale_price_samsung = sale_tag_samsung.get_text(strip=True) if sale_tag_samsung else None
        data_samsung["Sale Price"].append(sale_price_samsung)
        # -------- Offer text --------
        offer_tag_samsung = card_samsung.find("div", class_="UkUFwK")
        offer_samsung = offer_tag_samsung.get_text(strip=True) if offer_tag_samsung else "no offer"
        data_samsung["Offer"].append(offer_samsung)

In [188]:
# df_samsung=pd.DataFrame(data_samsung)
# print(df_samsung)
for k, v in data_samsung.items():
    print(k, len(v))

Product Name 960
Review & Ratings 960
Rating Number 960
Memory 960
Display 960
Camera 960
Processor 960
Water Resistance 960
Fast Charging 960
Wireless Charging 960
Warranty 960
Actual Price 960
Sale Price 960
Offer 960
Battery 960

In [189]:
df_samsung=pd.DataFrame(data_samsung)
print(df_samsung)

                                          Product Name  \
0            Samsung Galaxy F05 (Twilight Blue, 64 GB)
1                    Samsung Galaxy F07 (Green, 64 GB)
2                      Samsung M05 (Mint Green, 64 GB)
3                    Samsung Galaxy M07 (Black, 64 GB)
4                    Samsung Galaxy A06 (Black, 64 GB)
..                                                 ...
955    Samsung Galaxy Z Flip4 5G (Bora Purple, 128 GB)
956  Samsung Galaxy S24 Exynos 5G (Cobalt Violet, 5...
957           Samsung Galaxy S10 (Prism White, 512 GB)
958       Samsung Galaxy Z Flip4 5G (Graphite, 256 GB)
959    Samsung Galaxy Z Flip4 5G (Bora Purple, 256 GB)

                 Review & Ratings Rating Number  \
0    75,671 Ratings&4,082 Reviews           4.2
1        1,092 Ratings&62 Reviews           4.3
2       3,920 Ratings&163 Reviews           4.3
3             4 Ratings&0 Reviews           4.8
4          352 Ratings&21 Reviews           4.1
..                            ...           ...
955        378 Ratings&24 Reviews           3.9
956     8,336 Ratings&439 Reviews           4.6
957     1,941 Ratings&206 Reviews           4.5
958        378 Ratings&24 Reviews           3.9
959        378 Ratings&24 Reviews           3.9

                                                Memory  \
0          4 GB RAM | 64 GB ROM | Expandable Upto 1 TB
1          4 GB RAM | 64 GB ROM | Expandable Upto 2 TB
2    1 year manufacturer warranty for device and 6 ...
3    1 year manufacturer warranty for device and 6 ...
4          4 GB RAM | 64 GB ROM | Expandable Upto 1 TB
..                                                 ...
955                              8 GB RAM | 128 GB ROM
956                              8 GB RAM | 512 GB ROM
957     8 GB RAM | 512 GB ROM | Expandable Upto 512 GB
958                              8 GB RAM | 256 GB ROM
959                              8 GB RAM | 256 GB ROM

                                  Display  \
0        17.12 cm (6.74 inch) HD+ Display
1         17.02 cm (6.7 inch) HD+ Display
2             17.02 cm (6.7 inch) Display
3         17.02 cm (6.7 inch) HD+ Display
4         17.02 cm (6.7 inch) HD+ Display
..                                    ...
955  17.02 cm (6.7 inch) Full HD+ Display
956  15.75 cm (6.2 inch) Full HD+ Display
957  15.49 cm (6.1 inch) Quad HD+ Display
958  17.02 cm (6.7 inch) Full HD+ Display
959  17.02 cm (6.7 inch) Full HD+ Display

                                     Camera  \
0             50MP + 2MP | 8MP Front Camera
1             50MP + 2MP | 8MP Front Camera
2                          50MP Rear Camera
3             50MP + 2MP | 8MP Front Camera
4             50MP + 2MP | 8MP Front Camera
..                                      ...
955         12MP + 12MP | 10MP Front Camera
956  50MP + 10MP + 12MP | 12MP Front Camera
957         16MP + 12MP | 10MP Front Camera
958         12MP + 12MP | 10MP Front Camera
959         12MP + 12MP | 10MP Front Camera

                                  Processor Water Resistance Fast Charging  \
0                       Helio G85 Processor             None          None
1                       Helio G99 Processor             None          None
2                                      None             None          None
3                       Helio G99 Processor             None          None
4              Mediatek Helio G85 Processor             None          None
..                                      ...              ...           ...
955  Qualcomm Snapdragon 8+ Gen 1 Processor             None          None
956                   Exynos 2400 Processor             None          None
957                 Exynos 9 9820 Processor             None          None
958  Qualcomm Snapdragon 8+ Gen 1 Processor             None          None
959  Qualcomm Snapdragon 8+ Gen 1 Processor             None          None

    Wireless Charging                                           Warranty  \
0                None  1 Year Manufacturer Warranty for Device and 6 ...
1                None  1 Year Manufacturer Warranty for Device and 6 ...
2                None                                               None
3                None                                               None
4                None  1 Year Manufacturer Warranty for Device and 6 ...
..                ...                                                ...
955              None  1 Year Manufacturer Warranty for Device and 6 ...
956              None  1 Year Manufacturer Warranty for Device and 6 ...
957              None  Brand Warranty of 1 Year Available for Mobile ...
958              None  1 Year Manufacturer Warranty for Device and 6 ...
959              None  1 Year Manufacturer Warranty for Device and 6 ...

    Actual Price Sale Price     Offer                       Battery
0         ₹9,999     ₹6,499   35% off              5000 mAh Battery
1         ₹9,999     ₹6,749   32% off              5000 mAh Battery
2         ₹9,999     ₹7,495   25% off              5000 mAh Battery
3         ₹9,999     ₹7,638   23% off              5000 mAh Battery
4        ₹11,499     ₹7,777   32% off              5000 mAh Battery
..           ...        ...       ...                           ...
955    ₹1,01,999    ₹89,999   11% off  3700 mAh Lithium Ion Battery
956         None    ₹89,999  no offer              4000 mAh Battery
957         None    ₹92,000  no offer  3400 mAh Lithium-ion Battery
958    ₹1,06,999    ₹94,999   11% off  3700 mAh Lithium Ion Battery
959    ₹1,06,999    ₹94,999   11% off  3700 mAh Lithium Ion Battery

[960 rows x 15 columns]

In [190]:
df_samsung[10:40]

,Product Name,Review & Ratings,Rating Number,Memory,Display,Camera,Processor,Water Resistance,Fast Charging,Wireless Charging,Warranty,Actual Price,Sale Price,Offer,Battery
10,"Samsung Galaxy M06 5G (Blazing Black, 64 GB)",78 Ratings&4 Reviews,3.8,4 GB RAM | 64 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹12,499","₹8,662",30% off,5000 mAh Battery
11,"Samsung Galaxy A06 (Light Blue, 128 GB)",352 Ratings&21 Reviews,4.1,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Mediatek Helio G85 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹12,499","₹8,798",29% off,5000 mAh Battery
12,"Samsung Galaxy A06 (Gold, 128 GB)",352 Ratings&21 Reviews,4.1,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Mediatek Helio G85 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹12,499","₹8,799",29% off,5000 mAh Battery
13,"Samsung Galaxy F06 5G (Lit Violet, 64 GB)","35,185 Ratings&2,109 Reviews",4.1,4 GB RAM | 64 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹12,499","₹8,999",28% off,5000 mAh Battery
14,"Samsung Galaxy F06 5G (Bahama Blue, 64 GB)","35,185 Ratings&2,109 Reviews",4.1,4 GB RAM | 64 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹12,499","₹8,999",28% off,5000 mAh Battery
15,"Samsung Galaxy A06 5G (Light Green, 64 GB)","2,132 Ratings&136 Reviews",4.1,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.02 cm (6.7 inch) HD+ Display,50MP + 50MP | 2MP + 2MP Dual Front Camera,MEDIATEK Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹11,999","₹9,049",24% off,5000 mAh Battery
16,"Samsung Galaxy A14 (Black, 64 GB)",213 Ratings&14 Reviews,3.9,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,"Exynos 850, Octa Core Processor",None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹16,499","₹9,199",44% off,5000 mAh Battery
17,"Samsung M06 5G (Blazing Black, 128 GB)",767 Ratings&51 Reviews,4.1,4 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹13,999","₹9,321",33% off,5000 mAh Battery
18,"Samsung M06 5G (Sage Green, 128 GB)",767 Ratings&51 Reviews,4.1,4 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹13,999","₹9,398",32% off,5000 mAh Battery
19,"Samsung Galaxy A06 5G (Black, 64 GB)","2,132 Ratings&136 Reviews",4.1,4 GB RAM | 64 GB ROM,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹11,999","₹9,699",19% off,5000 mAh Li-ion Battery
20,"Samsung Galaxy A06 5G (Light Green, 64 GB)","2,132 Ratings&136 Reviews",4.1,4 GB RAM | 64 GB ROM,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹13,999","₹9,755",30% off,5000 mAh Li-ion Battery
21,"Samsung Galaxy F06 5G (Lit Violet, 128 GB)","35,185 Ratings&2,109 Reviews",4.1,4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹13,999","₹9,999",28% off,5000 mAh Battery
22,"Samsung Galaxy F06 5G (Bahama Blue, 128 GB)","35,185 Ratings&2,109 Reviews",4.1,4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹13,999","₹9,999",28% off,5000 mAh Battery
23,"Samsung M06 5G (Sage Green, 128 GB)",535 Ratings&40 Reviews,3.9,6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹13,500","₹11,153",17% off,5000 mAh Battery
24,"Samsung M06 5G (Blazing Black, 128 GB)",535 Ratings&40 Reviews,3.9,6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹13,500","₹11,190",17% off,5000 mAh Battery
25,"Samsung Galaxy F06 5G (Lit Violet, 128 GB)","17,685 Ratings&1,117 Reviews",4.2,6 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,499","₹11,499",25% off,5000 mAh Battery
26,"Samsung Galaxy F06 5G (Bahama Blue, 128 GB)","17,685 Ratings&1,117 Reviews",4.2,6 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,499","₹11,499",25% off,5000 mAh Battery
27,"Samsung Galaxy A06 5G (Black, 128 GB)","2,132 Ratings&136 Reviews",4.1,4 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,499","₹12,240",21% off,5000 mAh Li-ion Battery
28,"Samsung Galaxy M16 5G (Mint Green, 128 GB)",479 Ratings&15 Reviews,4.1,4 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹13,999","₹12,485",10% off,5000 mAh Battery
29,"Samsung Galaxy F16 5G (Vibing Blue, 128 GB)","4,094 Ratings&248 Reviews",4.1,4 GB RAM | 128 GB ROM,16.91 cm (6.657 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,999","₹12,499",21% off,5000 mAh Battery
30,"Samsung Galaxy M16 5G (Blush Pink, 128 GB)",479 Ratings&15 Reviews,4.1,4 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹13,999","₹12,585",10% off,5000 mAh Battery
31,"Samsung Galaxy A04 (Green, 128 GB)",246 Ratings&11 Reviews,3.8,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) HD+ Display,50MP + 2MP | 5MP Front Camera,Mediatek Helio P35 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,999","₹12,999",18% off,5000 mAh Lithium Ion Battery
32,"Samsung Galaxy F15 5G (Jazzy Green, 128 GB)","14,286 Ratings&1,109 Reviews",4.2,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,MediaTek Dimensity 6100+ Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,999","₹13,299",16% off,6000 mAh Lithium ion Battery
33,"Samsung Galaxy F15 5G (Ash Black, 128 GB)","14,286 Ratings&1,109 Reviews",4.2,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,MediaTek Dimensity 6100+ Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,999","₹13,499",15% off,6000 mAh Lithium ion Battery
34,"Samsung Galaxy M17 5G (Moonlight Silver, 128 GB)",17 Ratings&1 Reviews,4.3,1 year manufacturer warranty for device and 6 ...,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,None,"₹16,499","₹13,839",16% off,5000 mAh Battery
35,"Samsung Galaxy A16 5G (Blue Black, 128 GB)","3,758 Ratings&167 Reviews",4.2,6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹19,999","₹13,885",30% off,5000 mAh Battery
36,"Samsung Galaxy A16 5G (Light Green, 128 GB)","3,758 Ratings&167 Reviews",4.2,6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹19,999","₹13,969",30% off,5000 mAh Battery
37,"Samsung Galaxy F16 5G (Vibing Blue, 128 GB)","9,506 Ratings&552 Reviews",4.2,6 GB RAM | 128 GB ROM,16.91 cm (6.657 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,499","₹13,999",20% off,5000 mAh Battery
38,"Samsung Galaxy M16 5G (Blush Pink, 128 GB)","1,101 Ratings&54 Reviews",4.2,6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,None,None,None,None,1 Year Manufacturer Warranty for Phone and 6 M...,"₹16,809","₹13,999",16% off,5000 mAh Battery
39,"Samsung Galaxy F16 5G (Bling Black, 128 GB)","9,506 Ratings&552 Reviews",4.2,6 GB RAM | 128 GB ROM,16.91 cm (6.657 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,Dimensity 6300 Processor,None,None,None,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,499","₹13,999",20% off,5000 mAh Battery

In [191]:
df_samsung.to_csv("D:/web scraping/scraped excel sheet/filtered_samsung_page_data.csv",index=False)